name: iOS Cloud Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm ci
          npm run build --prod

      - name: Setup iOS Project
        run: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          npx cap sync ios
          npx cap update ios

      # Create Fastlane directory structure
      - name: copy Fastlane Configuration and Scripts
        run: |
          cd config
          cp -R fastlane/* ../ios/fastlane/
          cp -R Gemfile ../ios/

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Install Pod Dependencies
        run: |
          cd ios/App
          pod install --repo-update

      - name: Setup Fastlane Environment
        run: |
          cd ios
          sudo gem install bundler
          bundle install

          # Configure CI mode
          bundle exec fastlane run configure_ci

      - name: Run Fastlane Deployment
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          FASTLANE_SKIP_UPDATE_CHECK: "true"
          FASTLANE_HIDE_CHANGELOG: "true"
        run: |
          cd ios
          bundle exec fastlane ci_deploy
