name: iOS Cloud Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Shallow clone for speed

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Install Dependencies
        run: |
          npm ci
          npm run build --prod

      - name: Setup iOS Project
        run: |
          npx cap sync ios
          cd ios/App
          pod install --repo-update

      - name: Setup Fastlane
        run: |
          cd ios
          gem install bundler
          bundle install

      - name: Run Fastlane Deployment
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          cd ios
          bundle exec fastlane ci_deploy
